image: docker:latest
services:
  - docker:dind

stages:
  - build-pre
  - deploy-pre
  - build-prod

build-pre:
  stage: build-pre
  variables:
    workspace: utils-private
    name: simulator_company_static
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - pwd
    - docker build . -f Dockerfile -t $CI_REGISTRY/$workspace/$name:latest  
    - docker push $CI_REGISTRY/$workspace/$name:latest
    - docker push $CI_REGISTRY/$workspace/$name:$CI_COMMIT_TAG
  only:
    - main
  tags:
    - gitlab

deploy-pre:
  stage: deploy-pre
  image: centos
  script: 
    - mkdir -p ~/.ssh && chmod 700 ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
    - ssh ${SSH_USER}@${SSH_HOST} "docker login -u \"$CI_REGISTRY_USER\" -p \"$CI_REGISTRY_PASSWORD\" $CI_REGISTRY && docker pull $CI_REGISTRY/utils-private/CI_PROJECT_TITLE:latest"
    - set +e
    - ssh ${SSH_USER}@${SSH_HOST} "docker stop $CI_PROJECT_TITLE"
    - ssh ${SSH_USER}@${SSH_HOST} "docker rm $CI_PROJECT_TITLE"
    - set -e
    - ssh ${SSH_USER}@${SSH_HOST} "docker run -p 3005:3000 --restart=always -d --name $CI_PROJECT_TITLE --privileged -t docker-hub.middleware.biz/utils-private/$CI_PROJECT_TITLE:latest /bin/bash"
  only:
    - main
  tags:
    - gitlab